//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMQ.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("testMQ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratch-AA-S
        ///Scratch-AA-Minor
        ///Scratch-AA-Major
        ///Scratch-AA-Other2
        ///Scratch-AA-Other1
        ///Scratch-A-S1
        ///Scratch-A-S2
        ///Scratch-A-Minor
        ///Scratch-A-Major
        ///Scratch-A-Other3
        ///Scratch-A-Other2
        ///Scratch-A-Other1
        ///Scratch-A-WearedHomeButton
        ///Scratch-B-S1
        ///Scratch-B-S2
        ///Scratch-B-Minor
        ///Scratch-B-Major
        ///Scratch-B-Other3
        ///Scratch-B-Other2
        ///Scratch-B-Other1
        ///Scratch-C-S1
        ///Scratch-C-S2
        ///Scratch-C-Minor
        ///Scratch-C-Major
        ///Scratch-C-Other3
        ///Scratch-C-Other2
        ///Scratch-C-Other1
        ///Nick-AA-S
        ///Nick-AA-Minor
        ///Nick-AA-Major
        ///Nick-AA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keys {
            get {
                return ResourceManager.GetString("keys", resourceCulture);
            }
        }
    }
}
